const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('#header'),menuBtn=$('.menu-toggle'),nav=$('.main-nav'),backTop=$('.back-top');
const closeMenu=()=>{nav.classList.remove('open');menuBtn.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-label','Open navigation');document.body.classList.remove('menu-open')};
menuBtn.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menuBtn.classList.toggle('open',open);menuBtn.setAttribute('aria-expanded',String(open));menuBtn.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.body.classList.toggle('menu-open',open)});
$$('.main-nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>70);backTop.classList.toggle('show',scrollY>650)});backTop.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const sections=$$('main section[id]'),links=$$('.main-nav a');const setActive=()=>{let current='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))};addEventListener('scroll',setActive);
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>revealObserver.observe(el));

$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const filter=btn.dataset.filter;$$('.tour-card').forEach(card=>card.classList.toggle('hidden',filter!=='all'&&card.dataset.category!==filter))}));

const modal=$('#contentModal'),modalContent=$('#modalContent'),modalClose=$('.modal-close');let modalTrigger;
function openModal(html,trigger){modalTrigger=trigger;modalContent.innerHTML=html;modal.showModal();modalClose.focus()}
function closeModal(){modal.close();modalTrigger?.focus()}
modalClose.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});modal.addEventListener('cancel',e=>{e.preventDefault();closeModal()});
const packageImages={'Cultural Triangle':'sigiriya-real.jpg','Island Romance':'mirissa-real.jpg','Wildlife & Adventure':'elephant-real.jpg','Beach & Relaxation':'mirissa-real.jpg','Luxury Island Highlights':'galle-real.jpg','Highland Explorer':'train-real.jpg','Grand Ceylon Journey':'tea-real.jpg','Yala Safari Escape':'elephant-real.jpg'};
$$('.itinerary-btn').forEach(btn=>btn.addEventListener('click',()=>{const name=btn.dataset.tour,p=packageData[name],image=packageImages[name]||'hero-real.jpg';openModal(`<article class="package-modal"><header class="package-modal-hero" style="background-image:linear-gradient(0deg,rgba(5,28,47,.88),rgba(5,28,47,.08)),url('assets/images/${image}')"><p>Private Sri Lanka journey</p><h2>${name}</h2><div class="modal-package-meta"><span>${p.duration}</span><span>${p.pace} pace</span><span>${p.price}</span></div></header><div class="package-modal-body"><main class="package-main"><section class="package-overview"><p class="eyebrow">Journey overview</p><p class="package-lead">${p.summary}</p><div class="route-line"><b>Route</b><span>${p.route}</span></div></section><section><div class="package-section-heading"><p class="eyebrow">Your itinerary</p><h3>Day by day</h3></div><div class="itinerary-days timeline">${p.days.map((d,i)=>`<div><span class="day-badge">${p.duration==='1 day'?'Stop':i+1}</span><p><b>${p.duration==='1 day'?'Journey stage':'Day '+(i+1)}</b>${d}</p></div>`).join('')}</div></section></main><aside class="package-sidebar"><div class="package-summary"><p class="summary-label">At a glance</p><dl><div><dt>Duration</dt><dd>${p.duration}</dd></div><div><dt>From</dt><dd>${p.price}</dd></div><div><dt>Best for</dt><dd>${p.bestFor}</dd></div><div><dt>Travel pace</dt><dd>${p.pace}</dd></div></dl><button class="btn modal-plan">Customise this journey</button></div><details class="package-accordion" open><summary>What's included</summary><ul class="included">${p.includes.map(x=>`<li>${x}</li>`).join('')}</ul></details><details class="package-accordion"><summary>Not included</summary><ul class="excluded">${p.excludes.map(x=>`<li>${x}</li>`).join('')}</ul></details><p class="package-note"><b>Price note</b> Starting price only. Final cost depends on dates, group size, stays, vehicle and activities.</p></aside></div></article>`,btn);$('.modal-plan',modal).addEventListener('click',()=>{closeModal();prefillTour(name)})}));
$('.open-story').addEventListener('click',e=>openModal(`<p class="eyebrow">People behind your journey</p><h2>Local insight, personal care.</h2><h3>Anjali Perera — Senior Travel Designer</h3><p>Anjali turns traveller wish-lists into beautifully paced routes, balancing Sri Lanka's icons with quiet discoveries.</p><h3>Dinesh Fernando — Operations Manager</h3><p>Dinesh keeps every detail moving smoothly, from trusted guides to last-minute changes on the road.</p><h3>Kavindu Silva — Senior Driver-Guide</h3><p>Kavindu brings history, humour and a genuine love of his island to every mile.</p>`,e.currentTarget));
$$('.policy-btn').forEach(btn=>btn.addEventListener('click',()=>openModal(`<p class="eyebrow">Ceylora Journeys</p><h2>${btn.dataset.policy}</h2><p>This demonstration website respects visitor privacy and does not transmit form data to a server. In a production website, this page would explain data collection, booking terms, cancellation conditions and responsible-travel commitments in full.</p><p>For assessment purposes, all business details, reviews and offers shown here are fictional.</p>`,btn)));

function prefillTour(name){const form=$('#inquiryForm');form.elements.tour.value=name;$('#plan').scrollIntoView({behavior:'smooth'});setTimeout(()=>form.elements.name.focus(),600)}
$('#tripFinder').addEventListener('submit',e=>{e.preventDefault();const fields=[$('#finderMonth'),$('#finderDuration'),$('#finderGuests'),$('#finderInterest')];const invalid=fields.find(f=>!f.value);if(invalid){invalid.focus();invalid.reportValidity();return}const form=$('#inquiryForm');form.elements.month.value=$('#finderMonth').value;form.elements.duration.value=$('#finderDuration').value;form.elements.travellers.value=$('#finderGuests').value;form.elements.message.value=`Main interest: ${$('#finderInterest').value}`;$('#plan').scrollIntoView({behavior:'smooth'})});

const counterRules={finderDays:{min:1,max:30,hidden:'finderDuration',format:n=>`${n} ${n===1?'day':'days'}`},finderTravellers:{min:1,max:12,hidden:'finderGuests',format:n=>`${n} ${n===1?'traveller':'travellers'}`},planDays:{min:1,max:30,format:n=>`${n} ${n===1?'day':'days'}`}};
$$('[data-counter]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.counter,output=$(`#${id}`),rule=counterRules[id],change=button.dataset.action==='increase'?1:-1,next=Math.min(rule.max,Math.max(rule.min,Number(output.value||output.textContent)+change));output.value=next;output.textContent=next;if(rule.hidden)$(`#${rule.hidden}`).value=rule.format(next);if(id==='planDays')planData.duration=rule.format(next)}));
const planData={interests:[],duration:'7 days',style:'',month:'',guests:''};let planStep=1;
$$('.choices.multi button').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('selected');planData.interests=$$('.choices.multi button.selected').map(x=>x.textContent);$('.plan-step[data-step="1"] .next-step').disabled=!planData.interests.length}));
$$('.choices.single').forEach(group=>$$('button',group).forEach(b=>b.addEventListener('click',()=>{$$('button',group).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const step=+b.closest('.plan-step').dataset.step;if(step===2)planData.duration=b.textContent;if(step===3)planData.style=b.textContent;$('.next-step',b.closest('.plan-step')).disabled=false})));
$$('.next-step').forEach(btn=>btn.addEventListener('click',()=>{planStep++;$$('.plan-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===planStep));$$('.planner-progress span').forEach((s,i)=>s.classList.toggle('active',i<planStep))}));
$('#completePlan').addEventListener('click',()=>{planData.month=$('#planMonth').value;planData.guests=$('#planGuests').value;const f=$('#inquiryForm');f.elements.month.value=planData.month;f.elements.duration.value=planData.duration;f.elements.travellers.value=planData.guests;f.elements.message.value=`Interests: ${planData.interests.join(', ')}\nTravel style: ${planData.style}`;$('#plan').scrollIntoView({behavior:'smooth'})});

$$('.faq-item>button').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.parentElement,open=item.classList.contains('open');$$('.faq-item').forEach(i=>{i.classList.remove('open');$('button',i).setAttribute('aria-expanded','false')});if(!open){item.classList.add('open');btn.setAttribute('aria-expanded','true')}}));

let reviewIndex=0;const slides=$$('.review-slide'),dots=$$('.review-dots button');function showReview(i){reviewIndex=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===reviewIndex));dots.forEach((d,n)=>d.classList.toggle('active',n===reviewIndex))}$('#nextReview').addEventListener('click',()=>showReview(reviewIndex+1));$('#prevReview').addEventListener('click',()=>showReview(reviewIndex-1));dots.forEach(d=>d.addEventListener('click',()=>showReview(+d.dataset.slide)));

$('#inquiryForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,status=$('.form-status',form);status.textContent='';if(!form.checkValidity()){form.reportValidity();const first=$$('[required]',form).find(x=>!x.validity.valid);first?.focus();status.textContent='Please complete the highlighted required fields.';return}const data=new FormData(form);const message=[
  'NEW CEYLORA JOURNEYS INQUIRY','',
  `Name: ${data.get('name')}`,
  `Email: ${data.get('email')}`,
  `Phone / WhatsApp: ${data.get('phone')}`,
  `Travel month: ${data.get('month')}`,
  `Trip duration: ${data.get('duration')}`,
  `Travellers: ${data.get('travellers')}`,
  `Preferred journey: ${data.get('tour')}`,
  `Trip ideas: ${data.get('message')||'Not specified'}`
].join('\n');const whatsappUrl=`https://wa.me/94717526757?text=${encodeURIComponent(message)}`;status.textContent='Your inquiry is ready. WhatsApp is opening—tap Send to deliver it to our travel designer.';status.style.color='#123d35';const opened=window.open(whatsappUrl,'_blank','noopener,noreferrer');if(!opened)window.location.href=whatsappUrl});
$('#newsletter').addEventListener('submit',e=>{e.preventDefault();const email=$('#newsletterEmail');if(!email.checkValidity()){email.reportValidity();return}$('#newsletterStatus').textContent='Thank you. Your email has been added to this website demonstration.';e.currentTarget.reset()});
$('#year').textContent=new Date().getFullYear();
